### ISSUE TITLE
[Enhancement] Remove the children field from serialized tree object

### ISSUE THREAD

**Issue by PenguinWithATie** [clementwanjau/tree-ds#12]
Removing the children should reduce the size of the serialized object  and this information is possible to reconstruct given only data about the parents

I understand this change is non trivial and im willing to help deliver it.

Please give it some thought thanks

Edit: its worth mentioning this will slow down deserialization, but it could be worth it to save space

**Comment by clementwanjau** [comment]
I would prefer a feature gate so that you can opt in since different users may have different priorities. To you it may be space to someone else it may be speed.

**Comment by clementwanjau** [comment]
This has been been addressed in `v0.1.5`. You can now enable the `compact_serde` feature alongside `serde` and this will optimize the serialized data for space. 

> Note that serializing a single node in compact node will permanently lose the children information since the node is encapsulated and does not know of anything about other nodes. 

You can however serialize a tree in compact mode and it will properly reconstruct the hierarchy of the nodes.
